services:
  postgresql:
    image: postgres:14
    hostname: postgresql
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: conduktor-console
      POSTGRES_USER: conduktor
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U conduktor"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - conduktor-network

  conduktor-console:
    image: conduktor/conduktor-console:1.39.0
    ports:
      - "8080:8080"
    volumes:
      - conduktor_data:/var/conduktor
    environment:
      CDK_ORGANIZATION_NAME: ${CDK_ORGANIZATION_NAME:-my-organization}
      CDK_ADMIN_EMAIL: ${CDK_ADMIN_EMAIL}
      CDK_ADMIN_PASSWORD: ${CDK_ADMIN_PASSWORD}
      CDK_DATABASE_URL: postgresql://conduktor:${POSTGRES_PASSWORD}@postgresql:5432/conduktor-console
      CDK_MONITORING_CORTEX-URL: http://conduktor-monitoring:9009/
      CDK_MONITORING_ALERT-MANAGER-URL: http://conduktor-monitoring:9010/
      CDK_MONITORING_CALLBACK-URL: http://conduktor-console:8080/monitoring/api/
      CDK_MONITORING_NOTIFICATIONS-CALLBACK-URL: http://localhost:8080
    depends_on:
      postgresql:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - conduktor-network

  conduktor-monitoring:
    image: conduktor/conduktor-console-cortex:1.39.0
    environment:
      CDK_CONSOLE-URL: "http://conduktor-console:8080"
    volumes:
      - cortex_data:/var/conduktor-cortex
    restart: unless-stopped
    networks:
      - conduktor-network

volumes:
  pg_data:
  conduktor_data:
  cortex_data:

networks:
  conduktor-network:
    driver: bridge
